ElasticCaptainSmackDown/ElasticCaptainSmackDown/Models/Captain.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElasticCaptainSmackDown.Models
{
    public class Captain
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Models/CaptainContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ElasticCaptainSmackDown.Models
{
    public class CaptainContext : DbContext
    {
        public CaptainContext() 
            : base (Util.SqlHelper.GetConnectionString(Util.ConfigHelper.DataSource, string.Format(Util.ConfigHelper.DatabaseName, "Captain")))
        {
            
        }

        public DbSet<Captain> Captains { get; set; }

    }

    public class CaptainInitalizer : CreateDatabaseIfNotExists<CaptainContext>
    {
        protected override void Seed(CaptainContext context)
        {
            base.Seed(context);

            for (int i = 0; i < 100; i++)
            {
                context.Captains.Add(new Captain()
                {
                    Name = $"Captain {i:N0}"
                });
            }

            context.SaveChanges();
        }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Models/Vote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElasticCaptainSmackDown.Models
{
    public class Vote
    {
        public int ID { get; set; }
        public int Captain { get; set; }
        public DateTime Placed { get; set; }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Models/VoteContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace ElasticCaptainSmackDown.Models
{
    public class VoteContext : DbContext
    {
        public VoteContext(string server, string database) 
            : base (Util.SqlHelper.GetConnectionString(server, database))
        {

        }

        public DbSet<Vote> Votes { get; set; }

    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/ViewModels/Captain/IndexViewModel.cs
using ElasticCaptainSmackDown.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElasticCaptainSmackDown.ViewModels.Captain
{
    public class IndexViewModel
    {
        public IndexViewModel()
        {
            Captains = new List<IndexViewModelCaptain>();
        }
        public List<IndexViewModelCaptain> Captains { get; set; }
    }

    public class IndexViewModelCaptain
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int Votes { get; set; }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Controllers/CaptainController.cs
using ElasticCaptainSmackDown.Models;
using Microsoft.Azure.SqlDatabase.ElasticScale.Query;
using Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElasticCaptainSmackDown.Controllers
{
    public class CaptainController : Controller
    {
        CaptainContext _captainContext = null;
        RangeShardMap<int> _shardMap = null;

        public CaptainController(CaptainContext captainContext, RangeShardMap<int> shardMap)
        {
            _captainContext = captainContext;
            _shardMap = shardMap;
        }

        // GET: Captain
        public ActionResult Index()
        {
            Dictionary<int, int> votes = new Dictionary<int, int>();

            //Perform a multi shard query to tally all the votes
            // Get the shards to connect to
            var shards = _shardMap.GetShards();

            // Create the multi-shard connection
            using (var conn = new MultiShardConnection(shards, Util.SqlHelper.GetCredentialsConnectionString()))
            {
                // Create a simple command
                using (MultiShardCommand cmd = conn.CreateCommand())
                {
                    // Because this query is grouped by CustomerID, which is sharded,
                    // we will not get duplicate rows.
                    cmd.CommandText = @"SELECT Captain, COUNT(*) AS Votes FROM [dbo].[Votes] GROUP BY [Captain]";

                    // Allow for partial results in case some shards do not respond in time
                    cmd.ExecutionPolicy = MultiShardExecutionPolicy.PartialResults;

                    // Allow the entire command to take up to 30 seconds
                    cmd.CommandTimeout = 30;

                    // Execute the command. 
                    // We do not need to specify retry logic because MultiShardDataReader will internally retry until the CommandTimeout expires.
                    using (MultiShardDataReader reader = cmd.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            votes.Add(reader.GetInt32(0), reader.GetInt32(1));
                        }
                    }
                }
            }


            var vm = new ViewModels.Captain.IndexViewModel();

            foreach (var captain in _captainContext.Captains)
            {
                int voteCount = 0;
                votes.TryGetValue(captain.ID, out voteCount);

                vm.Captains.Add(new ViewModels.Captain.IndexViewModelCaptain()
                {
                    ID = captain.ID,
                    Name = captain.Name,
                    Votes = voteCount
                });
            }

            return View(vm);
        }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Controllers/HomeController.cs
using ElasticCaptainSmackDown.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElasticCaptainSmackDown.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Controllers/VoteController.cs
using ElasticCaptainSmackDown.App_Start;
using ElasticCaptainSmackDown.Models;
using ElasticCaptainSmackDown.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Practices.Unity;

namespace ElasticCaptainSmackDown.Controllers
{
    public class VoteController : Controller
    {

        // GET: Vote
        [HttpGet]
        public ActionResult Cast(int captain)
        {
            var shardMap = ShardHelper.CreateOrGetRangeShardMap();
            var shardMapping = shardMap.GetMappingForKey(captain);

            var container = UnityConfig.GetConfiguredContainer();

            var voteContext = container.Resolve<VoteContext>(shardMapping.Shard.ToString(),
                new ParameterOverride("server", shardMapping.Shard.Location.DataSource),
                new ParameterOverride("database", shardMapping.Shard.Location.Database));

            voteContext.Votes.Add(new Vote()
            {
                Captain = captain,
                Placed = DateTime.UtcNow
            });
            voteContext.SaveChanges();

            ViewBag.CaptainID = captain;

            return View();
        }
    }
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Views/Captain/Index.cshtml
@model ElasticCaptainSmackDown.ViewModels.Captain.IndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>The Captains</h2>

<ul>
    @foreach (var cap in Model.Captains)
    {
        <li>@Html.ActionLink(cap.Name, "Cast", "Vote",  new { captain = cap.ID }, null)  - @cap.Votes</li>
    }
</ul>

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Elastic Captain Smack Down</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Elastic Captain Smack Down", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Captains", "Index", "Captain")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Elastic Captain Smack Down</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ElasticCaptainSmackDown/ElasticCaptainSmackDown/Views/Vote/Cast.cshtml
@{
    ViewBag.Title = "Cast";
}

<h2>Vote Cast for Captain ID @ViewBag.CaptainID</h2>